### ISSUE TITLE
Support non-relational dependencies

### ISSUE THREAD

**Issue by bk-equityzen** [netzkolchose/django-computedfields#10]
This library would be great if it could support arbitrary models that aren't related to the computed model. E.g. Maybe something like

```py
class UnrelatedModel(models.Model):
    is_active = models.BooleanField()

class ComputedModel(ComputedFieldsModel):
    @computed(
        models.BooleanField(),
        depends=[
            "UnrelatedModel#is_active",
        ],
    )
    def foo(self, depends_instances):
        if depends_instances[0].is_active:
            return True
```

**Comment by jerch** [comment]
@bk-equityzen Already thought myself about extending the depends rules to non-related models and even to further generalize it to arbitrary data sinks, which can announce value changes and provide data access somehow.

Why I did not do it (yet?): Every use case I came up with ended up being "static" data from outside in a sense, that it is a hardcoded dependency which always could be written by some manager code like:
```python
...
if (outer_dep_changed):
    for elem in ComputedModel.objects.filter(...):
        elem.save()
...
```

Not sure how your example is intended to work - will `depends_instances` change over time? If not, you could also write it as:
```python
class UnrelatedModel(models.Model):
    is_active = models.BooleanField()

class ComputedModel(ComputedFieldsModel):
    rel = models.ForeignKey('UnrelatedModel')
    @computed(models.BooleanField(), depends=["rel#is_active"])
    def foo(self):
        if self.rel.is_active:
            return True
```
and make sure, that save always sets `rel` to the first entry of that other model.

If `depends_instances` may change over time, well then it gets more tricky, because the computed field would not work as a property anymore. `compute('fieldname')` deals under the hood with the method execution, it could theoretically take more arguments, but they have to be provided somehow during `Model.save` (which calls into `compute`). What would work though - precurry `compute` with additional args on model class level (which kinda makes those args class- and/or invocation wide):
1. this would work: set different values once per computed field invocation ("classwide" if done for all model instances)
  ```python
  outer_dep_value = 123
  for elem in ComputedModel.objects.filter(...):
      elem.compute('foo', outer_dep_value)  # all selected instances get the same args
  ```
2. this would not work: individual instances takes individual args
  ```python
  outer_dep_value_a = 123
  outer_dep_value_b = 456
  outer_dep_value_n = ...
  for elem in ComputedModel.objects.filter(...):
      elem.compute('foo', outer_dep_value_n)  # every instance gets some individual value
  ```

While 1. can be transformed into the declarative style of the `@computed` decorator 2. cannot. If you think about 2. for a moment - well its basically an individual dep to some other data. Thats what computedfields already does, but you have to provide some field relation to it.
And 1. is again what I described above - it always can be done with some manager code + signal handling.

So the question is - is it worth to implement those arbitrary outer deps logic with the limits above? Maybe you have some real world examples, where this would help alot?

**Comment by bk-equityzen** [comment]
The main thing I prefer about this library is its way of keeping all the dependencies in one place. Having manager code elsewhere makes it so that you no longer know all the dependencies of a computed field.

I do like the idea of an arbitrary data sink. I could see it being announced by a signal on an unrelated model and be able to handle any logic desired that triggers the data sink. This also allows a dev to easily search for any publishers of that data sink.

The code might look something like this:

```python
class ComputedModel(ComputedFieldsModel):
    @computed(
        models.BooleanField(),
        subscribed=[
            "trigger1",
        ],
    )
    def foo(self, data_sinks):
        if data_sinks[0] == True:
            return True

@receiver(signals.post_save, sender=UnrelatedModel)
def some_change_hook(sender, instance, **kwargs):
    publish_trigger("trigger1", instance.is_active)

```

A real world use case I had was a global logic switch, where if `UnrelatedModel.is_active`  is set to `False`, I want a bunch of models' computed fields to switch to different logic.

@jerch

**Comment by jerch** [comment]
@bk-equityzen The signal subscription idea looks good. It would open the computed model to arbitrary actions.

Still have to think about it, how to put the `subscribed` into shape and whether it is feasible to work with querysets here (subselections by some predicate) or if it always has to be model wide invocation. I'd like to hear your ideas in this regard (and well, it should not end up as an declarative programming language).

**Comment by jerch** [comment]
@bk-equityzen I postpone dealing with this idea until the basics are done. Currently there are still way to many unfortunate circumstances to get straight for "classical ORM dependencies".
