### ISSUE TITLE
Shortcut to detect all changes in a model

### ISSUE THREAD

**Issue by bk-equityzen** [netzkolchose/django-computedfields#11]
This would reduce a lot of repeated `depends` E.g. Maybe something like

```py
class SourceModel(models.Model):
    field1 = models.BooleanField()
    field2 = models.BooleanField()

class ComputedModel(ComputedFieldsModel):
    fk = models.ForeignKey(SourceModel)
    @computed(
        models.BooleanField(),
        depends=[
            "fk#*",
        ],
    )
    def foo(self):
        return fk.field1 and fk.field2
```

**Comment by jerch** [comment]
@bk-equityzen Yes, the depends listing got somewhat out of hand. Btw older versions only had the simplified depends string, where a model notion would always resolve all non computed fields and only computed fields on related models would need the explicit fieldname. But I had to change that, since `save` takes an update_fields argument, that was not covered by that deps resolver (and would run into cycling updates for certain cases).

I think I can do a your star variant, if computed fields itself are excluded from star:
```python
class A(ComputedFieldsModel):
    a = ...
    b = ...

    @computed(...)
    def c(self):
        return self.a + self.b

class B(ComputedFieldsModel):
    rel_a = models.ForeignKey('A')

    @computed(..., depends=['real_a#*'])
    def simple(self):
        return self.rel_a.a + self.rel_a.b

    @computed(..., depends=['rel_a#*', 'rel_a#c']) # make field c explicit
    def complicated(self):
        return self.rel_a.a + self.rel_a.b + self.rel_a.c
```

Here the field `B.simple` only refers to normal fields, thus `'real_a#*'` is sufficient. `B.complicated` also refers to another computed field `A.c`, which has to be listed explicitly.

Would this work for you? Note that a star variant, that also includes computed fields from the beginning, is only possible, if I forbid inter model computed field deps (which would limit the functionality alot).

**Comment by bk-equityzen** [comment]
Thanks for explaining the complexity here. How about if we structure the `depends` a little and allow for some of these special expansions?

E.g.

```python
class A(ComputedFieldsModel):
    a = ...
    b = ...

    @computed(...)
    def c(self):
        return self.a + self.b

class B(ComputedFieldsModel):
    rel_a = models.ForeignKey('A')

    @computed(..., depends=[
        ('rel_a', ['__all_non_computed__']), # Doesn't include computed
    ])
    def simple(self):
        return self.rel_a.a + self.rel_a.b

    @computed(..., depends=[
        ('rel_a', ['__all__']), # Includes computed
    ])
    def complicated(self):
        return self.rel_a.a + self.rel_a.b + self.rel_a.c
```

Even this structure without the special expansions would DRY quite a bit already

**Comment by jerch** [comment]
@bk-equityzen Hmm yes, I like your last suggestion as `[('rel_a', ['field1', 'field2', 'field3'])]` more than the star idea, it only needs enhanced capabilities in the depends argument parsing, def. the way to go. Feel free to open a PR if you want to do it yourself.

**Comment by jerch** [comment]
@bk-equityzen Some minor update on this from my side:

Currently it is still possible to cover non computed fields in a depends string by skipping any field notion, thus this should work:

```python
class A(ComputedFieldsModel):
    a = ...
    b = ...

    @computed(...)
    def c(self):
        return self.a + self.b

class B(ComputedFieldsModel):
    rel_a = models.ForeignKey('A')

    # no field notion needed (short form)
    @computed(..., depends=['rel_a']) 
    def simple(self):
        return self.rel_a.a + self.rel_a.b

    # comp field need explicit listing
    # other fields on 'rel_a' are covered automatically
    @computed(..., depends=['rel_a.c'])
    def complicated(self):
        return self.rel_a.a + self.rel_a.b + self.rel_a.c
```

This is possible, since the update resolver does not yet take primitive local fields into account for any optimizations. Still the docs currently discourage these short forms, mainly for an easy to comprehend API ("if it depends on that field, list it") and the ability to do further optimizations based on that information later on. I plan on doing more sophisticated optimizations with #17 and gonna re-eval your ideas there.

In the meantime you can use the short forms as listed above.

**Comment by jerch** [comment]
@bk-equityzen Re-evaled the ideas here and actually need a proper way to declared dependencies to fields on the same model to solve #20. I think this layout will do (your last suggestion):
```python
depends = (
    ('self', ('name', 'comp1')),        # deps to fields on own model 
    ('relA', ('field1', 'field2')),     # deps to fields on relA
    ('relA.relB', ('f1', 'f2'))         # deps to fields on relA->relB
)
```
This structure has several benefits:
- can be tested on startup for correct relations and fieldnames (awkward currently)
- can solve / re-order evaluation of computed fields with deps on the same model (currently not possible)
- enforce to list all dep fields (which makes `update_fields` working, even on the same model)
- opens the door to further optimizations later on (like only fetching certain values during updates)
