### ISSUE TITLE
unexpected `object has no attribute 'compute'` error

### ISSUE THREAD

**Issue by simkimsia** [netzkolchose/django-computedfields#61]
i now have this error message `object has no attribute 'compute'`

```
hl = WBSLinkageLineItem.objects.get(pk=96)
hl.is_used # this shows False which is expected
hl.compute('is_used') # I expect this to give me True but now gives me the no attribute error
hl.save() # didn't even get this far
```

This works tho... so is the documentation outdated or?
```
hl = WBSLinkageLineItem.objects.get(pk=96)
hl.is_used # this shows False which is expected
hl.save() # works
hl.is_used # this shows True which is expected
```

**Comment by jerch** [comment]
Ah right, thx for spotting this. Yes the docs are outdated, `compute` is a separate import from model now.

**Comment by simkimsia** [comment]
oh .. erm can show me how? then i can update the docs. I will also add an example of the depends on child model. My way of paying back

**Comment by jerch** [comment]
Works now like that:

```python
from computedfields.models import compute
...
value = compute(MyModel, 'fieldname')
```

**Comment by StriveForBest** [comment]
> Works now like that:
> 
> ```python
> from computedfields.models import compute
> ...
> value = compute(MyModel, 'fieldname')
> ```
> 
> The whole computed logic was moved into a separate resolver object, thus there is no direct call on the model anymore. The idea behind this was to get it working with any model class removing `ComputedFieldsModel`, but that was not a good idea in the end due to issues with `save` overloads, thus the subclass is still needed, but has not much functionality anymore.

for some reason it doesn't work if used in migration
```python
def resync_work_current_status(apps, schema_editor):
    sys.stdout.write(f'{os.linesep}{bcolors.HEADER}Computing Work.current_status, it will take a while...{bcolors.ENDC}')
    Work = apps.get_model('works', 'Work')
    # WorkStatus = apps.get_model('works', 'WorkStatus')
    # :meth:`computedfields.models.update_dependent` does not seem to work if ran from migration, using the slow method
    # update_dependent(Work.objects.all(), update_fields=['current_status'])
    for work in Work.objects.filter(current_status='').order_by('id'):
        compute(work, 'current_status')
        work.save(update_fields=['current_status'])
        sys.stdout.write(
            f'{os.linesep}  {bcolors.OKGREEN}SUCCESS{bcolors.ENDC}: '
            f'Updating Work with id {work.id} current_status to "{work.current_status}".{bcolors.ENDC}'
        )
```

does nothing... why?

**Comment by jerch** [comment]
@StriveForBest Migrations are a tough topic for computed fields, mainly because the resolver expects fully loaded model classes from django. Thats not given for migrations, due to their ability to do schema migrations they have quite a different view on the db side of things. Thus I had to deactivate any resolver attempts during migrations.

There are two ways to get something like autopopulating computed fields with/after migrations:
- use the default argument of the field (works as with any other concrete model field)
- after done with the migration, run `update_dependent(queryet_containing_affected_entries)` for all affected models (or call `updatedata` if this gets exhausting for many affected models)
